---
stages:
  - build

build:
  stage: build
  image: golang:latest
  variables:
    GOOS: linux
    GOARCH: amd64
    GO11MODULE: 'on'
  before_script:
    - RUN go get -u -v github.com/gobuffalo/packr/v2/packr2
  script:
    - make clean release
